.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. imcoin_qt test_imcoin_qt
clean: FORCE
	$(MAKE) -C .. imcoin_qt_clean test_imcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_imcoin_qt_check
imcoin-qt imcoin-qt.exe: FORCE
	 $(MAKE) -C .. imcoin_qt
